
# FROM zshusers/zsh as zsh_source

FROM linuxserver/code-server
# nix repo (include pkgs) would too slow
RUN apt-get update
RUN apt-get install -y tree zsh fzf

COPY /root /

# COPY --from=zsh_source /usr/bin/zsh /usr/bin/zsh

VOLUME [ "/vsix" ]
