#!/usr/bin/with-contenv bash

git clone --branch config https://github.com/huang12zheng/docker-code-server /config

mkdir -p /config/{extensions,data,workspace,.ssh}
mkdir -p /tmp/extensions
chown -R abc:abc /tmp/extensions
chmod +r /vsix

if [ -n "${SUDO_PASSWORD}" ] || [ -n "${SUDO_PASSWORD_HASH}" ]; then
    echo "setting up sudo access"
    if ! grep -q 'abc' /etc/sudoers; then
        echo "adding abc to sudoers"
        echo "abc ALL=(ALL:ALL) ALL" >> /etc/sudoers
    fi
    if [ -n "${SUDO_PASSWORD_HASH}" ]; then
        echo "setting sudo password using sudo password hash"
        sed -i "s|^abc:\!:|abc:${SUDO_PASSWORD_HASH}:|" /etc/shadow
    else
        echo "setting sudo password using SUDO_PASSWORD env var"
        echo -e "${SUDO_PASSWORD}\n${SUDO_PASSWORD}" | passwd abc
    fi
fi

[[ ! -f /config/.bashrc ]] && \
    cp /root/.bashrc /config/.bashrc
[[ ! -f /config/.profile ]] && \
    cp /root/.profile /config/.profile

# permissions
if [ -f "/usr/bin/find" ] && [ -f "/usr/bin/xargs" ]; then
    CORES=$(nproc --all)

    chown -R abc:abc /config/
else
    # Set permissions on data mount
    # do not decend into the workspace
    chown -R abc:abc "$(ls /config -I workspace)"
    chown abc:abc /config/workspace
fi
